#!/bin/bash

set -e

sudo dnf update -y

sudo dnf install -y git unzip tar gzip

# Install kubectl
KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)

curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"

chmod +x kubectl
sudo mv kubectl /usr/local/bin/

# Install eksctl
ARCH=amd64
PLATFORM=$(uname -s)_$ARCH

curl --silent --location \
"https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_${PLATFORM}.tar.gz" \
| tar xz -C /tmp

sudo mv /tmp/eksctl /usr/local/bin

# Verify
kubectl version --client
eksctl version
